'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace requestqueueWsProd
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="requestqueueWsProd.Service1Soap")>  _
    Public Interface Service1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CreateRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CreateRequest(ByVal req As requestqueueWsProd.EITQRRequest) As requestqueueWsProd.EITResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CreateRequest", ReplyAction:="*")>  _
        Function CreateRequestAsync(ByVal req As requestqueueWsProd.EITQRRequest) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateRequest(ByVal req As requestqueueWsProd.EITQRRequest) As requestqueueWsProd.EITResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateRequest", ReplyAction:="*")>  _
        Function UpdateRequestAsync(ByVal req As requestqueueWsProd.EITQRRequest) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateApplicationArguments", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateApplicationArguments(ByVal RQ As String, ByVal args As String) As requestqueueWsProd.EITResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateApplicationArguments", ReplyAction:="*")>  _
        Function UpdateApplicationArgumentsAsync(ByVal RQ As String, ByVal args As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RestartRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RestartRequest(ByVal RQ_ID As String) As requestqueueWsProd.EITResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RestartRequest", ReplyAction:="*")>  _
        Function RestartRequestAsync(ByVal RQ_ID As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/StopRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function StopRequest(ByVal RQ_ID As String) As requestqueueWsProd.EITResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/StopRequest", ReplyAction:="*")>  _
        Function StopRequestAsync(ByVal RQ_ID As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RetrieveRequests", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function RetrieveRequests(ByVal ApplicationName As String, ByVal statuses() As String) As requestqueueWsProd.EITQRRequest()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/RetrieveRequests", ReplyAction:="*")>  _
        Function RetrieveRequestsAsync(ByVal ApplicationName As String, ByVal statuses() As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITQRRequest())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelRequest(ByVal RQ_ID As String) As requestqueueWsProd.EITResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CancelRequest", ReplyAction:="*")>  _
        Function CancelRequestAsync(ByVal RQ_ID As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getServers", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getServers() As requestqueueWsProd.EITServer()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getServers", ReplyAction:="*")>  _
        Function getServersAsync() As System.Threading.Tasks.Task(Of requestqueueWsProd.EITServer())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getApplications", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getApplications() As requestqueueWsProd.EITApplication()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getApplications", ReplyAction:="*")>  _
        Function getApplicationsAsync() As System.Threading.Tasks.Task(Of requestqueueWsProd.EITApplication())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getRequest", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getRequest(ByVal rq_id As String) As requestqueueWsProd.EITQRRequest
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getRequest", ReplyAction:="*")>  _
        Function getRequestAsync(ByVal rq_id As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITQRRequest)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getApplicationsDataTable", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getApplicationsDataTable(ByVal ServerName As String, ByVal ApplicationId As String, ByVal StatusRequired() As String, ByVal newer As Date, ByVal older As Date) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getApplicationsDataTable", ReplyAction:="*")>  _
        Function getApplicationsDataTableAsync(ByVal ServerName As String, ByVal ApplicationId As String, ByVal StatusRequired() As String, ByVal newer As Date, ByVal older As Date) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setApplicationPosition", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function setApplicationPosition(ByVal REQ_ID As String, ByVal position As requestqueueWsProd.MovePosition) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setApplicationPosition", ReplyAction:="*")>  _
        Function setApplicationPositionAsync(ByVal REQ_ID As String, ByVal position As requestqueueWsProd.MovePosition) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDBHost", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function getDBHost() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getDBHost", ReplyAction:="*")>  _
        Function getDBHostAsync() As System.Threading.Tasks.Task(Of String)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EITQRRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private rtField As String
        
        Private appNameField As String
        
        Private emailField As String
        
        Private appArgumentsField As String
        
        Private idField As String
        
        Private serverIDField As String
        
        Private dedicatedappIdField As String
        
        Private requestTimeField As Date
        
        Private startTimeField As Date
        
        Private endTimeField As Date
        
        Private statusField As String
        
        Private errorDescriptionField As String
        
        Private appIdField As String
        
        Private userNameField As String
        
        Private totalSizeOfFilesField As Double
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Rt() As String
            Get
                Return Me.rtField
            End Get
            Set
                Me.rtField = value
                Me.RaisePropertyChanged("Rt")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property AppName() As String
            Get
                Return Me.appNameField
            End Get
            Set
                Me.appNameField = value
                Me.RaisePropertyChanged("AppName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("Email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property AppArguments() As String
            Get
                Return Me.appArgumentsField
            End Get
            Set
                Me.appArgumentsField = value
                Me.RaisePropertyChanged("AppArguments")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property ServerID() As String
            Get
                Return Me.serverIDField
            End Get
            Set
                Me.serverIDField = value
                Me.RaisePropertyChanged("ServerID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property DedicatedappId() As String
            Get
                Return Me.dedicatedappIdField
            End Get
            Set
                Me.dedicatedappIdField = value
                Me.RaisePropertyChanged("DedicatedappId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property RequestTime() As Date
            Get
                Return Me.requestTimeField
            End Get
            Set
                Me.requestTimeField = value
                Me.RaisePropertyChanged("RequestTime")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property StartTime() As Date
            Get
                Return Me.startTimeField
            End Get
            Set
                Me.startTimeField = value
                Me.RaisePropertyChanged("StartTime")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property EndTime() As Date
            Get
                Return Me.endTimeField
            End Get
            Set
                Me.endTimeField = value
                Me.RaisePropertyChanged("EndTime")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property ErrorDescription() As String
            Get
                Return Me.errorDescriptionField
            End Get
            Set
                Me.errorDescriptionField = value
                Me.RaisePropertyChanged("ErrorDescription")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property AppId() As String
            Get
                Return Me.appIdField
            End Get
            Set
                Me.appIdField = value
                Me.RaisePropertyChanged("AppId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("UserName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property TotalSizeOfFiles() As Double
            Get
                Return Me.totalSizeOfFilesField
            End Get
            Set
                Me.totalSizeOfFilesField = value
                Me.RaisePropertyChanged("TotalSizeOfFiles")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EITApplication
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private nameField As String
        
        Private urlField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
                Me.RaisePropertyChanged("Url")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EITServer
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private serverNameField As String
        
        Private numOfRunnableProcessField As Integer
        
        Private ipField As String
        
        Private applicationDedicatedField As String
        
        Private ressourceBalancedField As Boolean
        
        Private memoryField As Double
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property ServerName() As String
            Get
                Return Me.serverNameField
            End Get
            Set
                Me.serverNameField = value
                Me.RaisePropertyChanged("ServerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NumOfRunnableProcess() As Integer
            Get
                Return Me.numOfRunnableProcessField
            End Get
            Set
                Me.numOfRunnableProcessField = value
                Me.RaisePropertyChanged("NumOfRunnableProcess")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Ip() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
                Me.RaisePropertyChanged("Ip")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property ApplicationDedicated() As String
            Get
                Return Me.applicationDedicatedField
            End Get
            Set
                Me.applicationDedicatedField = value
                Me.RaisePropertyChanged("ApplicationDedicated")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property RessourceBalanced() As Boolean
            Get
                Return Me.ressourceBalancedField
            End Get
            Set
                Me.ressourceBalancedField = value
                Me.RaisePropertyChanged("RessourceBalanced")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Memory() As Double
            Get
                Return Me.memoryField
            End Get
            Set
                Me.memoryField = value
                Me.RaisePropertyChanged("Memory")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EITResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private applicationUrlField As String
        
        Private rtField As String
        
        Private appArgumentsField As String
        
        Private emailField As String
        
        Private serverNameField As String
        
        Private errorField As String
        
        Private statusField As String
        
        Private qR_IDField As String
        
        Private positionQueueField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ApplicationUrl() As String
            Get
                Return Me.applicationUrlField
            End Get
            Set
                Me.applicationUrlField = value
                Me.RaisePropertyChanged("ApplicationUrl")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property RT() As String
            Get
                Return Me.rtField
            End Get
            Set
                Me.rtField = value
                Me.RaisePropertyChanged("RT")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property AppArguments() As String
            Get
                Return Me.appArgumentsField
            End Get
            Set
                Me.appArgumentsField = value
                Me.RaisePropertyChanged("AppArguments")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("Email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property ServerName() As String
            Get
                Return Me.serverNameField
            End Get
            Set
                Me.serverNameField = value
                Me.RaisePropertyChanged("ServerName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property [Error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                Me.errorField = value
                Me.RaisePropertyChanged("Error")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property QR_ID() As String
            Get
                Return Me.qR_IDField
            End Get
            Set
                Me.qR_IDField = value
                Me.RaisePropertyChanged("QR_ID")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property PositionQueue() As Integer
            Get
                Return Me.positionQueueField
            End Get
            Set
                Me.positionQueueField = value
                Me.RaisePropertyChanged("PositionQueue")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Public Enum MovePosition
        
        '''<remarks/>
        Up
        
        '''<remarks/>
        Down
        
        '''<remarks/>
        Top
        
        '''<remarks/>
        Bottom
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Service1SoapChannel
        Inherits requestqueueWsProd.Service1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1SoapClient
        Inherits System.ServiceModel.ClientBase(Of requestqueueWsProd.Service1Soap)
        Implements requestqueueWsProd.Service1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function CreateRequest(ByVal req As requestqueueWsProd.EITQRRequest) As requestqueueWsProd.EITResult Implements requestqueueWsProd.Service1Soap.CreateRequest
            Return MyBase.Channel.CreateRequest(req)
        End Function
        
        Public Function CreateRequestAsync(ByVal req As requestqueueWsProd.EITQRRequest) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult) Implements requestqueueWsProd.Service1Soap.CreateRequestAsync
            Return MyBase.Channel.CreateRequestAsync(req)
        End Function
        
        Public Function UpdateRequest(ByVal req As requestqueueWsProd.EITQRRequest) As requestqueueWsProd.EITResult Implements requestqueueWsProd.Service1Soap.UpdateRequest
            Return MyBase.Channel.UpdateRequest(req)
        End Function
        
        Public Function UpdateRequestAsync(ByVal req As requestqueueWsProd.EITQRRequest) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult) Implements requestqueueWsProd.Service1Soap.UpdateRequestAsync
            Return MyBase.Channel.UpdateRequestAsync(req)
        End Function
        
        Public Function UpdateApplicationArguments(ByVal RQ As String, ByVal args As String) As requestqueueWsProd.EITResult Implements requestqueueWsProd.Service1Soap.UpdateApplicationArguments
            Return MyBase.Channel.UpdateApplicationArguments(RQ, args)
        End Function
        
        Public Function UpdateApplicationArgumentsAsync(ByVal RQ As String, ByVal args As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult) Implements requestqueueWsProd.Service1Soap.UpdateApplicationArgumentsAsync
            Return MyBase.Channel.UpdateApplicationArgumentsAsync(RQ, args)
        End Function
        
        Public Function RestartRequest(ByVal RQ_ID As String) As requestqueueWsProd.EITResult Implements requestqueueWsProd.Service1Soap.RestartRequest
            Return MyBase.Channel.RestartRequest(RQ_ID)
        End Function
        
        Public Function RestartRequestAsync(ByVal RQ_ID As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult) Implements requestqueueWsProd.Service1Soap.RestartRequestAsync
            Return MyBase.Channel.RestartRequestAsync(RQ_ID)
        End Function
        
        Public Function StopRequest(ByVal RQ_ID As String) As requestqueueWsProd.EITResult Implements requestqueueWsProd.Service1Soap.StopRequest
            Return MyBase.Channel.StopRequest(RQ_ID)
        End Function
        
        Public Function StopRequestAsync(ByVal RQ_ID As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult) Implements requestqueueWsProd.Service1Soap.StopRequestAsync
            Return MyBase.Channel.StopRequestAsync(RQ_ID)
        End Function
        
        Public Function RetrieveRequests(ByVal ApplicationName As String, ByVal statuses() As String) As requestqueueWsProd.EITQRRequest() Implements requestqueueWsProd.Service1Soap.RetrieveRequests
            Return MyBase.Channel.RetrieveRequests(ApplicationName, statuses)
        End Function
        
        Public Function RetrieveRequestsAsync(ByVal ApplicationName As String, ByVal statuses() As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITQRRequest()) Implements requestqueueWsProd.Service1Soap.RetrieveRequestsAsync
            Return MyBase.Channel.RetrieveRequestsAsync(ApplicationName, statuses)
        End Function
        
        Public Function CancelRequest(ByVal RQ_ID As String) As requestqueueWsProd.EITResult Implements requestqueueWsProd.Service1Soap.CancelRequest
            Return MyBase.Channel.CancelRequest(RQ_ID)
        End Function
        
        Public Function CancelRequestAsync(ByVal RQ_ID As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITResult) Implements requestqueueWsProd.Service1Soap.CancelRequestAsync
            Return MyBase.Channel.CancelRequestAsync(RQ_ID)
        End Function
        
        Public Function getServers() As requestqueueWsProd.EITServer() Implements requestqueueWsProd.Service1Soap.getServers
            Return MyBase.Channel.getServers
        End Function
        
        Public Function getServersAsync() As System.Threading.Tasks.Task(Of requestqueueWsProd.EITServer()) Implements requestqueueWsProd.Service1Soap.getServersAsync
            Return MyBase.Channel.getServersAsync
        End Function
        
        Public Function getApplications() As requestqueueWsProd.EITApplication() Implements requestqueueWsProd.Service1Soap.getApplications
            Return MyBase.Channel.getApplications
        End Function
        
        Public Function getApplicationsAsync() As System.Threading.Tasks.Task(Of requestqueueWsProd.EITApplication()) Implements requestqueueWsProd.Service1Soap.getApplicationsAsync
            Return MyBase.Channel.getApplicationsAsync
        End Function
        
        Public Function getRequest(ByVal rq_id As String) As requestqueueWsProd.EITQRRequest Implements requestqueueWsProd.Service1Soap.getRequest
            Return MyBase.Channel.getRequest(rq_id)
        End Function
        
        Public Function getRequestAsync(ByVal rq_id As String) As System.Threading.Tasks.Task(Of requestqueueWsProd.EITQRRequest) Implements requestqueueWsProd.Service1Soap.getRequestAsync
            Return MyBase.Channel.getRequestAsync(rq_id)
        End Function
        
        Public Function getApplicationsDataTable(ByVal ServerName As String, ByVal ApplicationId As String, ByVal StatusRequired() As String, ByVal newer As Date, ByVal older As Date) As System.Data.DataTable Implements requestqueueWsProd.Service1Soap.getApplicationsDataTable
            Return MyBase.Channel.getApplicationsDataTable(ServerName, ApplicationId, StatusRequired, newer, older)
        End Function
        
        Public Function getApplicationsDataTableAsync(ByVal ServerName As String, ByVal ApplicationId As String, ByVal StatusRequired() As String, ByVal newer As Date, ByVal older As Date) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements requestqueueWsProd.Service1Soap.getApplicationsDataTableAsync
            Return MyBase.Channel.getApplicationsDataTableAsync(ServerName, ApplicationId, StatusRequired, newer, older)
        End Function
        
        Public Function setApplicationPosition(ByVal REQ_ID As String, ByVal position As requestqueueWsProd.MovePosition) As String Implements requestqueueWsProd.Service1Soap.setApplicationPosition
            Return MyBase.Channel.setApplicationPosition(REQ_ID, position)
        End Function
        
        Public Function setApplicationPositionAsync(ByVal REQ_ID As String, ByVal position As requestqueueWsProd.MovePosition) As System.Threading.Tasks.Task(Of String) Implements requestqueueWsProd.Service1Soap.setApplicationPositionAsync
            Return MyBase.Channel.setApplicationPositionAsync(REQ_ID, position)
        End Function
        
        Public Function getDBHost() As String Implements requestqueueWsProd.Service1Soap.getDBHost
            Return MyBase.Channel.getDBHost
        End Function
        
        Public Function getDBHostAsync() As System.Threading.Tasks.Task(Of String) Implements requestqueueWsProd.Service1Soap.getDBHostAsync
            Return MyBase.Channel.getDBHostAsync
        End Function
    End Class
End Namespace
