'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ConfiguratorBuilder

    '''<summary>
    '''hfModelIcon_Groove_Turn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_Groove_Turn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_ISO_Turning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_ISO_Turning As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_Threading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_Threading As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_Milling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_Milling As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_Hole_Making control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_Hole_Making As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_Hole_Reaming control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_Hole_Reaming As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_Indexable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_Indexable As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_Solid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_Solid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_SolidEndmilsBallNose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_SolidEndmilsBallNose As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfModelIcon_SolidEndmilsSquare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfModelIcon_SolidEndmilsSquare As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txt1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfRepoprtsNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRepoprtsNames As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''wucTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wucTabs As Global.semiPrj.wucTab

    '''<summary>
    '''upPnlAll_Config control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPnlAll_Config As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''hfListViewLastSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfListViewLastSelected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lvMainApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvMainApp As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''SelectedMainIdIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedMainIdIndex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelectedMainIdFamily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedMainIdFamily As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackBi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackBi As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lvMainApp_Sub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvMainApp_Sub As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''SelectedSubIdIndex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedSubIdIndex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnBackCi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBackCi As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lvMainApp_SubSub control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvMainApp_SubSub As Global.System.Web.UI.WebControls.ListView
End Class
