'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Material

    '''<summary>
    '''wucTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wucTabs As Global.semiPrj.wucTab

    '''<summary>
    '''upPnlAll_Material control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPnlAll_Material As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dlMaterialMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlMaterialMain As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''dlMaterialMain1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlMaterialMain1 As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblSetMat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSetMat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvMaterials As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btmOenQbuilder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btmOenQbuilder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''SelectedColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedColor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelectedForColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectedForColor As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfColumnRepeat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfColumnRepeat As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfRepoprtsNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRepoprtsNames As Global.System.Web.UI.WebControls.HiddenField
End Class
