'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Prices

    '''<summary>
    '''lblAlertDeleteQut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertDeleteQut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlertDeleteQut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertDeleteQut1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlertDeleteQutButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertDeleteQutButton As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBacktoEditing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBacktoEditing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlertDeleteFirsLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertDeleteFirsLine As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlertDeleteQutButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertDeleteQutButton1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBacktoEditing1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBacktoEditing1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTitleEmailQut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTitleEmailQut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlertEmailQut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertEmailQut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSerToc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSerToc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFindSNOffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFindSNOffer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''wucTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wucTabs As Global.semiPrj.wucTab

    '''<summary>
    '''upPnlAll_Prices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPnlAll_Prices As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnSubmitMessagePrices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmitMessagePrices As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''fuFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuFile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''fuOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuOrder As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''lblSendTemporaryIdx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSendTemporaryIdx As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hfMinQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMinQuantity As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''btnSendTemporaryId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendTemporaryId As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSendTemporaryIdTech control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendTemporaryIdTech As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFillGPHided control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFillGPHided As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDoDeleteQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoDeleteQuotation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CuptureiFrame control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CuptureiFrame As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRefreshN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshN As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BsonTextQutNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BsonTextQutNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BsonTextQutNoX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BsonTextQutNoX As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BsonTextID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BsonTextID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDOCSFileId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOCSFileId As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOCSFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOCSFileName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDOCSFolderPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDOCSFolderPath As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''AllRedy3DAlertShows control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AllRedy3DAlertShows As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDoTryToFindDrawing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoTryToFindDrawing As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDoDraw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDoDraw As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hfSecondsAllCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSecondsAllCount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSecondsStartCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSecondsStartCount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnDoDeleteDocumentCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoDeleteDocumentCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDoDeleteDocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDoDeleteDocument As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfSubmetted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubmetted As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPricesVers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPricesVers As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPriceOrdered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPriceOrdered As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPricesSelectedVers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPricesSelectedVers As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTemporaryQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTemporaryQuotation As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfRepoprtsNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRepoprtsNames As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSelectFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectFile As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSelectedQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedQuantity As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSelectedEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedEmail As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCustomerOrderN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCustomerOrderN As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCustomerItemN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCustomerItemN As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCustomerReqN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCustomerReqN As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSelectedPhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSelectedPhoneNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFilesCoun control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFilesCoun As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfcapiQuoteMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfcapiQuoteMessage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfQuotationSaved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfQuotationSaved As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMyQuotations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMyQuotations As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hf3DlineSecond control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf3DlineSecond As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hf3DlineFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf3DlineFirst As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubmitAlertLine1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubmitAlertLine1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfTheSerialNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfTheSerialNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubmitAlertLine2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubmitAlertLine2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubmitAlertLine3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubmitAlertLine3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubmitAlertLine4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubmitAlertLine4 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubmitAlertLine5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubmitAlertLine5 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfplaceanOrderTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfplaceanOrderTitle As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfplaceanOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfplaceanOrder As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfadddocument control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfadddocument As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfViwe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfViwe As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hf3DlabelView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf3DlabelView As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hf2DlabelView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hf2DlabelView As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfClose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfClose As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfBSONfolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfBSONfolder As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfExistQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfExistQ As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDeleteQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDeleteQ As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfBackToEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfBackToEdit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfInsertEmailAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfInsertEmailAdd As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfDeleteQContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfDeleteQContent As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lblParamsDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParamsDes As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lvParams control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvParams As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''lblQDtitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQDtitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQDtitleSM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQDtitleSM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQutNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQutNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblItemDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblItemDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDelv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDelv As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDelivery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDelivery As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblcurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomerCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerCurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreatedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LblCreateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblCreateDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLastUpdateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLastUpdateDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpiryDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExpDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomerNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustoName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustoName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubsidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubsidiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubsAddre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubsAddre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContactDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblISCARSubsidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISCARSubsidiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubsidiaryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubsidiaryAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaymenttTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaymenttTerms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblShippingMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShippingMethod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upPrices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPrices As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblPriceTempAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceTempAlert As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlViewHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlViewHistory As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblViHis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViHis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pnlViewOrdered control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlViewOrdered As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ValidationSummary3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary3 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''ValidationSummaryLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummaryLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvPrices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPrices As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''gvPrices_Temp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvPrices_Temp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnSaveQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveQuotation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''pnlClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlClient As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlServer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnDelQut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelQut As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCreateSendMail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateSendMail2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtFlagPricesChanged control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFlagPricesChanged As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rptLanguagesListPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptLanguagesListPrice As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblSelectRepLang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectRepLang As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upPnlAll_Documents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPnlAll_Documents As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''upPnlAll_Documentsdiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPnlAll_Documentsdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvDocuments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDocuments As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblMaxFileSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaxFileSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btmVSI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btmVSI As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCreate_Report2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreate_Report2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSendMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendMail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSendMailHT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendMailHT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtEmailAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailAdd As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegularExpValidEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegularExpValidEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblQuotationDr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuotationDr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ifif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ifif As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''PdfView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PdfView As Global.System.Web.UI.HtmlControls.HtmlIframe

    '''<summary>
    '''txtPDFexist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDFexist As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPDFexistBSON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPDFexistBSON As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPlaceOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPlaceOrder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PanelParamList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelParamList As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dgvParamList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvParamList As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''vsMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsMessages As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btmDrawint3D control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btmDrawint3D As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCatiaDrawing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCatiaDrawing As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''VldUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VldUser As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''pnlbson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlbson As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ValidationSummary1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidationSummary1 As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkGPCOST control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGPCOST As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''labelC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents labelC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPdfViewsrc4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPdfViewsrc4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TabBSON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TabBSON As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Tab2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab2 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Tab2OnlySesstion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tab2OnlySesstion As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtAllReadyTriedtoBuildDrawing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAllReadyTriedtoBuildDrawing As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSelectQutstitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectQutstitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelectQutstitleS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectQutstitleS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstvSelectedPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstvSelectedPrice As Global.System.Web.UI.WebControls.DataList

    '''<summary>
    '''lblSelectQutstitle2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectQutstitle2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPlaceanOrderAttachFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlaceanOrderAttachFile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblApprovalDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblApprovalDocs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelect As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSelectMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbleadP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbleadP As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSelectPhoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSelectPhoneNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustomerOrderN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerOrderN1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomerOrderN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerOrderN1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustomerItemN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerItemN2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomerItemN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerItemN2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustomerAdditionalReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerAdditionalReq As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomerAdditionalReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerAdditionalReq As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCancelSelectQuantity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSelectQuantity As Global.System.Web.UI.WebControls.Button
End Class
