'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QuotationsList

    '''<summary>
    '''lblAlertPriceCh2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertPriceCh2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVVqut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVVqut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAlertPriceCh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertPriceCh1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''upPnlAll_QutList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPnlAll_QutList As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblToDuplicateBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToDuplicateBC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblToDuplicateQutNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToDuplicateQutNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblToRenewBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToRenewBC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblToRenewQutNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblToRenewQutNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeleteBranchCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteBranchCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDeleteQuotationNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeleteQuotationNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnDuplicateQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDuplicateQuotation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRenewQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRenewQuotation As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblFolderPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFolderPath As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''selecteddisplayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents selecteddisplayType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRedirectPrices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirectPrices As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfRepoprtsNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfRepoprtsNames As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''wucTabs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wucTabs As Global.semiPrj.wucTab

    '''<summary>
    '''lblmql control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmql As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSearchAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearchAll As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearchAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchAll As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''chkSearchOrderd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSearchOrderd As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSearchExpired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSearchExpired As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSearchSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSearchSubmit As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtConnect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConnect As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''AddtoMyQuotations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddtoMyQuotations As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divBS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBranch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddlCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lvQuotationListA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvQuotationListA As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''hfGridQutNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfGridQutNo As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfGridItemDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfGridItemDesc As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfQuotationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfQuotationDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfExpiryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfExpiryDate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfLastUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLastUpdate As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfReportLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfReportLanguage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfStatus As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfItemNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfItemNumber As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCustomerName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfduplicateTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfduplicateTitle As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfduplicateMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfduplicateMessage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfduplicateButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfduplicateButton As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfduplicateButtonCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfduplicateButtonCancel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPrevious As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfNext As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfFirst As Global.System.Web.UI.WebControls.HiddenField
End Class
