'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Transition

    '''<summary>
    '''formTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents formTr As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''PanelToHide4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelToHide4 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rb_Hmm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rb_Hmm As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rb_HInch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rb_HInch As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''paneltoHide3C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paneltoHide3C As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rbMMmain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbMMmain As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbInchmain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbInchmain As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ddlFamily_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFamily_MOD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lang_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lang_MOD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vers_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vers_MOD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlModel_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlModel_MOD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''sTool_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sTool_MOD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlModel_Items_MOD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlModel_Items_MOD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''StartModification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StartModification As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''QuotationListMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuotationListMod As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''paneltoHide1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paneltoHide1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lang control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lang As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''vers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFamilyPic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFamilyPic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''sTool control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sTool As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''itemNumbe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents itemNumbe As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''startConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents startConfig As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''paneltoHide2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paneltoHide2 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlCalcMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalcMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''paneltoHide3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents paneltoHide3 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''pnlRd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRd As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''btnConnectToGal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConnectToGal As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtMailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMailAddressNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMailAddressNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlRado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRado As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''rbEmailMickiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbEmailMickiv As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbEmailNataly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbEmailNataly As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbEmailTamar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbEmailTamar As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rbEmailBilal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbEmailBilal As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''dgvItems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvItems As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''imgLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLine As Global.System.Web.UI.WebControls.Image
End Class
