'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class wucTab

    '''<summary>
    '''btnProductType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProductType As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''divModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divModel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblProductType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProductTypeTEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductTypeTEXT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMaterial As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''divMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMaterial As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaterial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMaterialTEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMaterialTEXT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnParameters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnParameters As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''divParameters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divParameters As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblParameters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParameters As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblParametersTEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParametersTEXT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnGetQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetQuotation As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''divQuotations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQuotations As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblGetQuotation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGetQuotation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGetQuotationTEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGetQuotationTEXT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnRunMT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunMT As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRunBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunBL As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnRunPT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRunPT As Global.System.Web.UI.WebControls.Button
End Class
