'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SemiSTDMaster

    '''<summary>
    '''head control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''SM_Mastr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SM_Mastr As Global.AjaxControlToolkit.ToolkitScriptManager

    '''<summary>
    '''upPnlAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upPnlAll As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtMessagetxtMailName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessagetxtMailName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMessagetxtMailEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessagetxtMailEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMessagetxtMailCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessagetxtMailCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMessagetxtMailCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessagetxtMailCompanyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMessageContactU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessageContactU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMessageFeedBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessageFeedBack As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txthideshlogbutton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthideshlogbutton As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txthideshlogbuttonSelected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthideshlogbuttonSelected As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txttxtdivMyQut2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txttxtdivMyQut2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustomerNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustoName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustoName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblISCARSubsidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblISCARSubsidiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubsidiaryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubsidiaryAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPaymenttTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPaymenttTerms As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblShippingMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblShippingMethod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsalesperson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsalesperson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblsalespersonEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsalespersonEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldeskUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldeskUser As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbldeskUserEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldeskUserEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltechnicalPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltechnicalPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbltechnicalPersonEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltechnicalPersonEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hfMyAccountbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMyAccountbtn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMyQuotations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMyQuotations As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfbtn_ContactUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfbtn_ContactUs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfbtn_Feedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfbtn_Feedback As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfbtnUserG2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfbtnUserG2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hffontNewQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hffontNewQ As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfLogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLogOut As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfLogIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLogIn As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfMyAccountDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfMyAccountDetails As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCustomerNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCustomerNumber As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCustomerName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCustomerAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCustomerAddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubSidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubSidiary As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSubsidaryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSubsidaryAddress As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfContactDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfContactDetails As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPaymentTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPaymentTerms As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfShippingMethod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfShippingMethod As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfSalesPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfSalesPerson As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfEmail As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HfDeskUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HfDeskUser As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HfTechnicalPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HfTechnicalPerson As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftCountry As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftCompanyName As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftMessage As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftContactUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftContactUs As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftImprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftImprove As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftrelevantRes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftrelevantRes As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftiQuoteAdvisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftiQuoteAdvisor As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hftiwouldyouimprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hftiwouldyouimprove As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfbSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfbSubmit As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfbSend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfbSend As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfbCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfbCancel As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfPingCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfPingCaption As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfLanguageselected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfLanguageselected As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hfCloseMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCloseMaster As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnLanguageselected control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLanguageselected As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hfselectedBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfselectedBC As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btnloginUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnloginUserName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnloginUserNameVF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnloginUserNameVF As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divLoginout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divLoginout As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptLanguagesListCaptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptLanguagesListCaptions As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''lblMasterReporCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterReporCountry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''unitSwitch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents unitSwitch As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnUnitC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnitC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMasterEc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterEc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hlTransition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlTransition As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlPostBachAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlPostBachAdmin As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''hlUserCustomerConnect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlUserCustomerConnect As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''ImageButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnOpenHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOpenHome As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ph_Export control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ph_Export As Global.System.Web.UI.WebControls.PlaceHolder

    '''<summary>
    '''divMyQut2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMyQut2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnCloseMyQutDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseMyQutDiv As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTmyQut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTmyQut As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTpleaseLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTpleaseLogin As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnDivLogIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDivLogIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTinsertoffer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTinsertoffer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFindSN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFindSN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFind As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''divHelpMnu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divHelpMnu As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlGuideTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGuideTemp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlGuide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGuide As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lblBranchCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBranchCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnOpenQuotations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOpenQuotations As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnStartNewQ control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStartNewQ As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ContentPlaceHolderMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolderMain As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''ContentPlaceHolderTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContentPlaceHolderTemp As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''Footer1Ens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer1Ens As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Footer2Ens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer2Ens As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Footer3Ens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer3Ens As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Footer4Ens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Footer4Ens As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUserInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserInformation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnLogOnWithoutRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogOnWithoutRegistration As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnLogOnWithSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogOnWithSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSendFeedback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendFeedback As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnReportSubmitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReportSubmitID As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtFeed_Bpic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeed_Bpic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFeed_Apic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeed_Apic As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''btnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''reBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reBC As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ttrErepTr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ttrErepTr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''reBCDcod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents reBCDcod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''heBC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents heBC As Global.System.Web.UI.WebControls.Label
End Class
